### PR TITLE
refactor: Get rid of header_utils.ts

### PR DESCRIPTION
**Pull request by bgoscinski**
I noticed that most of the functions in header_utils.ts were not used and that setting header can be simplified by coercing `init.headers` to `Headers` instance. 

Feel free to close this if you don't like this refactor :)

### CODE REVIEW

**Comment by jd1378** [comment]
there's many ways to set headers other than the Headers instance, I wanted to support them all, that's why the file exists.

**Comment by jd1378** [comment]
are you sure it handles them all correctly ?

**Comment by jd1378** [comment]
yeah okay I guess this is fine as well, thanks for letting me know I could do this

**Comment by bgoscinski** [comment]
Yes, I think it handles all the ways because we delegate to `Headers` constructor that accepts optional `HeadersInit`. `RequestInit`'s `headers` property is declared also as `HeadersInit` so it's all compatible as far as I can tell :)

**Pull request merged**
